---
deployment:
  tasks:
    # Define o caminho de deploy
    - export DEPLOYPATH=/home2/hg722e44/public_html/
    
    # Verifica se o Node.js está disponível
    - which node || (echo "Node.js não encontrado. Instale Node.js no cPanel." && exit 1)
    
    # Navega para o diretório do repositório
    - cd $GIT_REPO_ROOT
    
    # Instala dependências (necessário para o build)
    - npm install --production=false
    
    # Gera o build do projeto
    - npm run build
    
    # Verifica se o build foi gerado com sucesso
    - test -d dist || (echo "Erro: pasta dist não foi criada pelo build" && exit 1)
    
    # Remove arquivos antigos do diretório de deploy (mantém config.js se existir)
    - if [ -f $DEPLOYPATH/config.js ]; then /bin/cp $DEPLOYPATH/config.js $DEPLOYPATH/config.js.backup; fi
    - /bin/rm -rf $DEPLOYPATH*
    - if [ -f $DEPLOYPATH/config.js.backup ]; then /bin/mv $DEPLOYPATH/config.js.backup $DEPLOYPATH/config.js; fi
    
    # Copia todos os arquivos da pasta dist para public_html
    - /bin/cp -R $GIT_REPO_ROOT/dist/* $DEPLOYPATH
    
    # Copia o arquivo .htaccess do repositório (SEMPRE usa a versão do repositório)
    - if [ -f $GIT_REPO_ROOT/.htaccess ]; then /bin/cp $GIT_REPO_ROOT/.htaccess $DEPLOYPATH/.htaccess && echo ".htaccess copiado com sucesso"; else echo "Aviso: .htaccess não encontrado no repositório"; fi
    
    # Define permissões corretas
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
    
    # Limpa arquivos temporários (opcional)
    - echo "Deploy concluído com sucesso!"

